### PR TITLE
Specify package for code coverage

### PR DESCRIPTION
**Pull request by edwardlafoy**
Wanted to add the option to specify which target to gather coverage information about. When you have quite a few pods, this can take a significant amount of extra time if this parameter isn't include.

I'm not entirely sure how the yml options are read in the script, but from looking around on other steps, I _think_ this will work? 😄 

Thanks!

### CODE REVIEW

**Comment by viktorbenei** [comment]
Awesome! 

Inputs are passed as environment variables 😉

Which also means that your single quote around the input in the step.sh will not work, as single quoted texts are **not** expanded, it's treated as a text, as it is, by Bash

Another note: this might break the step if there's no argument for -J, but I'm not 100% sure how it handles an empty string as the value of -J

**Comment by viktorbenei** [comment]
Final note: you can run / test your version of the Step with the Bitrise CLI - for updated, more thorough description / guide see the step template's readme : https://github.com/bitrise-steplib/step-template/blob/master/README.md#how-to-use-this-step

More for ourselves: we should update this Step's readme 😉

**Comment by viktorbenei** [comment]
Please update this Pull Request if you want it to be merged - it conflicts with the current state of the repository.

**Comment by stevepeak** [comment]
@edwardlafoy Codecov will soon be detecting the `-J` value automatically! Ping me back if you would like to test this feature out. Thank you!

**Comment by viktorbenei** [comment]
Sounds fantastic @stevepeak , and sure, we'd like to test it if possible! ;)

**Comment by stevepeak** [comment]
@edwardlafoy @viktorbenei Thank you! If you don't mind trying these two implementations out to get the ProjectName:

```
xcodebuild -showBuildSettings 2>/dev/null | grep -i "^\s*PRODUCT_NAME" | sed -e 's/.*= \(.*\)/\1/')
```

and

```
find . -name '*.xcworkspace' -maxdepth 1 -exec basename -s '.xcworkspace' {} \;
```

Let me know of what results you find 👍

**Comment by viktorbenei** [comment]
will be addressed in a more generic way by https://github.com/bitrise-io/steps-codecov/pull/3

**Comment by viktorbenei** [comment]
And of course, thanks for the contribution @edwardlafoy ! 😉

**Pull request closed without merging**
